name: SGSI_Build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://www.coolapk.com/link?url=https%3A%2F%2Fdownload.meizu.com%2FFirmware%2FFlyme%2Fmeizu18%2F9.3.6.0%2Fcn%2F20220816093509%2Ff3329633%2Fupdate.zip'
      ZIP_NAME:
        description: 'ZIP_NAME'
        required: true
        default: 'update.zip'
      OS_TYPE:
        description: 'OS_TYPE'
        required: true
        default: 'flyme'
      SGSI_TYPE:
        description: 'SGSI_TYPE(AB, A, or BOTH)'
        required: true
        default: 'AB'
      REPACK_NAME:
        description: 'REPACK_NAME'
        required: true
        default: 'ROM.7z'




jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main

      - name: Get variable configuration...
        run: |
          echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV

      - name: Clean up the environment‌‌...
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: Configuration Environment‌‌...
        run: |
          sudo apt-get install -y git wget git zip unzip curl axel

      - name: Get the OPT ..,
        run: |
          git clone --recurse-submodules https://github.com/XPHNature/Original_package_tool $GITHUB_WORKSPACE/Original_package_tool

      - name: Replace custom condensed content...
        run: |
          sudo chmod 777 -R $GITHUB_WORKSPACE/Original_package_tool

      - name: 下载ROM...
        run: |
          cd $GITHUB_WORKSPACE/Original_package_tool
          mkdir ./tmp
          wget -U "Mozilla/5.0" ${{ github.event.inputs.ROM_URL }} -O "$GITHUB_WORKSPACE/Original_package_tool/tmp/${{ github.event.inputs.ZIP_NAME }}"
          echo "zip_file: $(ls "$GITHUB_WORKSPACE/Original_package_tool/tmp/")"

      - name: Configuration tool environment...
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/Original_package_tool/setup.sh
          sudo bash $GITHUB_WORKSPACE/Original_package_tool/setup.sh
          sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
          java -version

      - name: Make AB type GSI‌‌...
        if: ${{ github.event.inputs.SGSI_TYPE }} == 'AB' || ${{ github.event.inputs.SGSI_TYPE }} == 'BOTH'
        run: |
          sudo bash $GITHUB_WORKSPACE/Original_package_tool/make.sh AB << EOF
          ${{ github.event.inputs.ZIP_NAME }}
          y #修复亮度
          y #PHH化
          y #一键删除NFC
          ${{ github.event.inputs.OS_TYPE }}
          y

      - name: Packing(AB)...
        if: ${{ github.event.inputs.SGSI_TYPE }} == 'AB' || ${{ github.event.inputs.SGSI_TYPE }} == 'BOTH'
        run: |
          cd $GITHUB_WORKSPACE/Original_package_tool
          pwd
          7za a -t7z -r AB_${{ github.event.inputs.REPACK_NAME }} X/system.img
          ls "AB_${{ github.event.inputs.REPACK_NAME }}"
          echo "--------------------------------------"
          ls
          echo "--------------------------------------"
          mkdir upload_ab
          echo "--------------------------------------"
          ls upload_ab
          echo "--------------------------------------"
          if [ $(ls -l AB_${{ github.event.inputs.REPACK_NAME }} | awk '{print $5}') -gt 2147483647 ]; then tar cvzpf - AB_${{ github.event.inputs.REPACK_NAME }} | split -d -b 1024m - upload_ab/AB_${{ github.event.inputs.REPACK_NAME }}; else mv AB_${{ github.event.inputs.REPACK_NAME }} upload_ab/AB_${{ github.event.inputs.REPACK_NAME }}; fi
          echo "--------------------------------------"
          ls upload_ab
          echo "--------------------------------------"

      - name: Upload to Release‌‌...
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "${{ github.workspace }}/Original_package_tool/upload_ab/*,${{ github.workspace }}/Tool-SGSI-build/upload_aonly/*"
          tag: "${{ github.event.inputs.REPACK_NAME }}_${{ env.BUILD_TIME }}"
          bodyFile: "${{ github.workspace }}/Original_package_tool/SGSI/build_info.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
